import React, { useState, useEffect } from 'react';
import { Hammer, Smartphone, Play, Download, Settings, Loader2 } from 'lucide-react';
import { useWorkspaceStore } from '../store/workspaceStore';

export const BuildPanel: React.FC = () => {
    const { workspaceRoot, setBottomPanelState } = useWorkspaceStore();
    const [building, setBuilding] = useState(false);
    const [devices, setDevices] = useState<any[]>([]);
    const [selectedDevice, setSelectedDevice] = useState<string | null>(null);
    const [loadingDevices, setLoadingDevices] = useState(false);
    const [installing, setInstalling] = useState(false);

    useEffect(() => {
        loadDevices();
        const interval = setInterval(loadDevices, 10000); // refresh every 10s
        return () => clearInterval(interval);
    }, []);

    const loadDevices = async () => {
        setLoadingDevices(true);
        const res = await window.electronAPI.executeCommand('adb.devices');
        if (res.success && res.data) {
            setDevices(res.data);
            if (res.data.length > 0 && !selectedDevice) {
                setSelectedDevice(res.data[0].id);
            } else if (res.data.length === 0) {
                setSelectedDevice(null);
            }
        }
        setLoadingDevices(false);
    };

    const handleBuild = async () => {
        if (!workspaceRoot) return;
        setBuilding(true);
        setBottomPanelState(true, 'terminal');
        
        const outputApkPath = `${workspaceRoot}/dist/app_release.apk`;
        
        const res = await window.electronAPI.executeCommand('build.run', {
            workspacePath: workspaceRoot,
            outputApkPath: outputApkPath
            // no keystore provided means debug keystore
        });

        if (res.success) {
            // Build ok
        }
        setBuilding(false);
    };

    const handleInstall = async () => {
        if (!workspaceRoot || !selectedDevice) return;
        setInstalling(true);
        setBottomPanelState(true, 'terminal');
        
        // Find the apk in dist
        const res = await window.electronAPI.executeCommand('adb.install', {
            deviceId: selectedDevice,
            apkPath: `${workspaceRoot}/dist/app_release.apk`
        });

        setInstalling(false);
    };

    return (
        <div className="flex flex-col h-full overflow-y-auto">
            <div className="text-[11px] uppercase font-semibold text-ide-text-muted px-4 py-2 tracking-wider">Build & Run</div>
            
            <div className="p-4 flex flex-col gap-6">
                {/* Build Section */}
                <div>
                    <h3 className="text-xs font-semibold text-ide-text-bright mb-3 flex items-center gap-2">
                        <Hammer size={14} /> Pipeline
                    </h3>
                    <button 
                        onClick={handleBuild}
                        disabled={building || !workspaceRoot}
                        className="w-full bg-ide-accent hover:bg-ide-accent/90 disabled:opacity-50 text-white rounded px-3 py-2 text-sm flex items-center justify-center gap-2 transition-colors shadow"
                    >
                        {building ? <Loader2 size={14} className="animate-spin" /> : <Play size={14} />} 
                        {building ? 'Building...' : 'Build APK'}
                    </button>
                    
                    <button 
                        disabled={installing || !selectedDevice || building}
                        onClick={handleInstall}
                        className="w-full mt-2 bg-ide-bg hover:bg-ide-hover disabled:opacity-50 border border-ide-border text-ide-text-bright rounded px-3 py-2 text-sm flex items-center justify-center gap-2 transition-colors"
                    >
                        {installing ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />}
                        {installing ? 'Installing...' : 'Install on Device'}
                    </button>
                </div>
                
                {/* Keystore Section */}
                <div>
                    <h3 className="text-xs font-semibold text-ide-text-bright mb-3">Keystore</h3>
                    <div className="text-xs text-ide-text-muted mb-2 bg-ide-bg p-2 rounded border border-ide-border">
                        <div className="font-mono text-[11px] mb-1">Using debug.keystore</div>
                        <div className="text-[10px] opacity-70">Auto-generated by Uber-APK-Signer</div>
                    </div>
                    <button className="text-ide-accent text-xs flex items-center gap-1 hover:underline">
                        <Settings size={12} /> Configure Keystore...
                    </button>
                </div>

                {/* Devices Section */}
                <div className="flex-1">
                    <h3 className="text-xs font-semibold text-ide-text-bright mb-3 flex items-center gap-2">
                        <Smartphone size={14} /> Devices
                    </h3>
                    <div className="flex flex-col gap-2">
                        {devices.length === 0 ? (
                            <div className="bg-ide-bg border border-ide-border rounded p-3 text-center text-xs text-ide-text-muted flex flex-col items-center gap-2">
                                <Smartphone size={24} className="opacity-50" />
                                <div>No devices found</div>
                                <div className="text-[10px]">Ensure USB Debugging is enabled</div>
                            </div>
                        ) : (
                            devices.map(dev => (
                                <div 
                                    key={dev.id} 
                                    className={`p-2 rounded border cursor-pointer transition-colors ${selectedDevice === dev.id ? 'bg-[#2a2d2e] border-ide-accent' : 'bg-ide-bg border-ide-border hover:border-[#3e3e42]'}`}
                                    onClick={() => setSelectedDevice(dev.id)}
                                >
                                    <div className="text-sm text-ide-text-bright font-medium flex justify-between items-center">
                                        <span>{dev.model}</span>
                                        <span className={`text-[10px] uppercase px-1.5 py-0.5 rounded ${dev.state === 'device' ? 'bg-green-500/20 text-green-400' : 'bg-yellow-500/20 text-yellow-400'}`}>
                                            {dev.state}
                                        </span>
                                    </div>
                                    <div className="text-xs text-ide-text-muted mt-1 font-mono">{dev.id}</div>
                                </div>
                            ))
                        )}
                    </div>
                    <button 
                        onClick={loadDevices}
                        disabled={loadingDevices}
                        className="w-full mt-3 text-xs text-ide-text-muted hover:text-white transition-colors flex justify-center items-center gap-1"
                    >
                        {loadingDevices ? <Loader2 size={12} className="animate-spin" /> : null}
                        Refresh Devices
                    </button>
                </div>
            </div>
        </div>
    );
};
